name: Backend CI/CD

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: krishi2210/todo-app

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set image tag
      - name: Set IMAGE TAG
        run: echo "IMAGE_TAG=${{ github.run_number }}" >> $GITHUB_ENV

      # 3. Install & Test
      - name: Install & Test
        run: |
          npm install
          npm test

      # 4. Docker login
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 5. Build image
      - name: Build Image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest

      # 6. Push image
      - name: Push Image
        run: |
          docker push $IMAGE_NAME:$IMAGE_TAG
          docker push $IMAGE_NAME:latest

      # 7. Setup SSH
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 8. Deploy
      - name: Deploy with Rollback
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_IP }} << 'EOF'

          IMAGE_NAME=krishi2210/todo-app
          IMAGE_TAG=${{ github.run_number }}

          echo "Cleanup old temp container..."
          docker rm -f todo-app-new || true

          echo "Pull latest image..."
          docker pull $IMAGE_NAME:$IMAGE_TAG

          echo "Saving previous image..."
          PREVIOUS=$(docker inspect todo-app --format='{{.Config.Image}}' 2>/dev/null)

          echo "Starting new container (canary)..."
          docker run -d --name todo-app-new -p 8001:3001 --restart always $IMAGE_NAME:$IMAGE_TAG

          echo "Waiting for health check..."
          for i in {1..20}; do
            if curl -f http://18.203.231.12:8000/health > /dev/null; then
              echo "Health check passed"
              break
            fi
            sleep 3
          done

          if curl -f http://18.203.231.12:8000/health > /dev/null; then
              echo "Deploy success → switching containers"

              docker stop todo-app || true
              docker rm todo-app || true

              docker stop todo-app-new
              docker rm todo-app-new

              docker run -d --name todo-app -p 8000:8000 --restart always $IMAGE_NAME:$IMAGE_TAG

              echo "Cleaning old images..."
              docker image prune -af || true

          else
              echo "Health check failed → rollback"

              docker rm -f todo-app-new || true

              if [ ! -z "$PREVIOUS" ]; then
                docker run -d --name todo-app -p 8000:8000 --restart always $IMAGE_NAME:$IMAGE_TAG
              else
                echo "No previous image found!"
              fi

              exit 1
          fi

          EOF